import React, { useState, useMemo } from 'react';
import { Card, Button, Input } from '@/components/common';
import { CodeBlock } from './CodeBlock';
import { useExport } from '@/hooks/useExport';
import { getEmailType } from '@/lib/validation';
import { CONSUMER_EMAIL_DOMAINS } from '@/lib/constants';

interface EmailResult {
  email: string;
  type: 'business' | 'consumer';
  domain: string;
}

export const EmailFilter: React.FC = () => {
  const [singleEmail, setSingleEmail] = useState('');
  const [bulkEmails, setBulkEmails] = useState('');
  const [results, setResults] = useState<EmailResult[]>([]);
  const { downloadJS, getTimestamp } = useExport();

  const allDomains = useMemo(
    () => [
      ...CONSUMER_EMAIL_DOMAINS.global,
      ...CONSUMER_EMAIL_DOMAINS.australia,
      ...CONSUMER_EMAIL_DOMAINS.regional,
    ],
    []
  );

  const singleResult = useMemo(() => {
    if (!singleEmail || !singleEmail.includes('@')) return null;
    return {
      email: singleEmail,
      type: getEmailType(singleEmail),
      domain: singleEmail.split('@')[1]?.toLowerCase() || '',
    };
  }, [singleEmail]);

  const handleBulkValidate = () => {
    const emails = bulkEmails
      .split(/[\n,;]+/)
      .map((e) => e.trim())
      .filter((e) => e.includes('@'));

    const validated = emails.map((email) => ({
      email,
      type: getEmailType(email),
      domain: email.split('@')[1]?.toLowerCase() || '',
    }));

    setResults(validated);
  };

  const businessCount = results.filter((r) => r.type === 'business').length;
  const consumerCount = results.filter((r) => r.type === 'consumer').length;

  const validationCode = `// Consumer Email Validation Function
// Generated by SignalStack

const CONSUMER_EMAIL_DOMAINS = ${JSON.stringify(allDomains, null, 2)};

/**
 * Check if an email address is from a consumer domain
 * @param {string} email - The email address to check
 * @returns {boolean} - True if consumer email, false if business
 */
function isConsumerEmail(email) {
  if (!email || typeof email !== 'string') return true;

  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return true; // Invalid email = treat as consumer

  return CONSUMER_EMAIL_DOMAINS.includes(domain);
}

/**
 * Get the email type for segment classification
 * @param {string} email - The email address to check
 * @returns {'business' | 'consumer'} - The email type
 */
function getEmailType(email) {
  return isConsumerEmail(email) ? 'consumer' : 'business';
}

/**
 * Get the value multiplier for an email address
 * @param {string} email - The email address
 * @param {number} businessMultiplier - Multiplier for business emails (default 1.5)
 * @param {number} consumerMultiplier - Multiplier for consumer emails (default 0.1)
 * @returns {number} - The value multiplier to apply
 */
function getEmailValueMultiplier(email, businessMultiplier = 1.5, consumerMultiplier = 0.1) {
  return isConsumerEmail(email) ? consumerMultiplier : businessMultiplier;
}

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { isConsumerEmail, getEmailType, getEmailValueMultiplier, CONSUMER_EMAIL_DOMAINS };
}`;

  const formValidationCode = `<!-- HTML Form with Email Validation -->
<form id="lead-form" onsubmit="return validateEmailBeforeSubmit(event)">
  <input
    type="email"
    id="email"
    name="email"
    required
    placeholder="Work email address"
  />
  <div id="email-warning" style="display: none; color: #b91c1c; font-size: 14px;">
    Please use your work email address for faster response.
  </div>
  <button type="submit">Submit</button>
</form>

<script>
function validateEmailBeforeSubmit(event) {
  const email = document.getElementById('email').value;
  const warning = document.getElementById('email-warning');

  if (isConsumerEmail(email)) {
    warning.style.display = 'block';
    // Optional: prevent submission of consumer emails
    // event.preventDefault();
    // return false;
  } else {
    warning.style.display = 'none';
  }

  // Track the email type in your data layer
  window.dataLayer = window.dataLayer || [];
  window.dataLayer.push({
    'event': 'email_captured',
    'user_data': {
      'email_type': getEmailType(email)
    }
  });

  return true;
}
</script>`;

  return (
    <div className="space-y-6">
      <Card title="Consumer Email Filter">
        <p className="text-gray-600">
          Identify consumer vs business email addresses using a blocklist of {allDomains.length} consumer
          email domains. Use this to filter leads, adjust conversion values, and improve lead quality.
        </p>
      </Card>

      <Card title="Single Email Check">
        <div className="flex gap-4 items-end">
          <div className="flex-1">
            <Input
              label="Email Address"
              type="email"
              value={singleEmail}
              onChange={(e) => setSingleEmail(e.target.value)}
              placeholder="user@example.com"
            />
          </div>
          {singleResult && (
            <div
              className={`px-4 py-2 rounded-md text-sm font-medium ${
                singleResult.type === 'business'
                  ? 'bg-green-100 text-green-800'
                  : 'bg-red-100 text-red-800'
              }`}
            >
              {singleResult.type === 'business' ? 'Business Email' : 'Consumer Email'}
            </div>
          )}
        </div>
      </Card>

      <Card title="Bulk Email Validation">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Paste email addresses (one per line, or comma/semicolon separated)
            </label>
            <textarea
              className="w-full h-32 px-3 py-2 border border-gray-300 rounded-md focus:ring-primary-500 focus:border-primary-500"
              value={bulkEmails}
              onChange={(e) => setBulkEmails(e.target.value)}
              placeholder="john@company.com&#10;jane@gmail.com&#10;bob@enterprise.io"
            />
          </div>
          <Button variant="primary" onClick={handleBulkValidate}>
            Validate Emails
          </Button>

          {results.length > 0 && (
            <div className="mt-4">
              <div className="flex gap-4 mb-4">
                <div className="px-4 py-2 bg-green-50 rounded-md">
                  <span className="text-green-800 font-medium">{businessCount}</span>
                  <span className="text-green-600 ml-1">Business</span>
                </div>
                <div className="px-4 py-2 bg-red-50 rounded-md">
                  <span className="text-red-800 font-medium">{consumerCount}</span>
                  <span className="text-red-600 ml-1">Consumer</span>
                </div>
                <div className="px-4 py-2 bg-gray-50 rounded-md">
                  <span className="text-gray-800 font-medium">
                    {((businessCount / results.length) * 100).toFixed(1)}%
                  </span>
                  <span className="text-gray-600 ml-1">Business Rate</span>
                </div>
              </div>

              <div className="max-h-64 overflow-y-auto border border-gray-200 rounded-md">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50 sticky top-0">
                    <tr>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                        Email
                      </th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                        Domain
                      </th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                        Type
                      </th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {results.map((result, i) => (
                      <tr key={i}>
                        <td className="px-4 py-2 text-sm text-gray-900">{result.email}</td>
                        <td className="px-4 py-2 text-sm text-gray-500">{result.domain}</td>
                        <td className="px-4 py-2">
                          <span
                            className={`inline-flex px-2 py-1 text-xs font-medium rounded ${
                              result.type === 'business'
                                ? 'bg-green-100 text-green-800'
                                : 'bg-red-100 text-red-800'
                            }`}
                          >
                            {result.type}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </Card>

      <Card title="JavaScript Validation Function" subtitle="Add this to your website for client-side validation">
        <CodeBlock
          code={validationCode}
          language="javascript"
          title="email-validation.js"
          showLineNumbers
          onDownload={() => downloadJS(validationCode, `email-validation-${getTimestamp()}.js`)}
        />
      </Card>

      <Card title="Form Integration Example" subtitle="Example HTML form with email type validation">
        <CodeBlock code={formValidationCode} language="javascript" title="form-example.html" showLineNumbers />
      </Card>

      <Card title="Blocked Domains List">
        <p className="text-gray-600 mb-4">
          The following {allDomains.length} domains are classified as consumer email providers:
        </p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2 max-h-48 overflow-y-auto p-2 bg-gray-50 rounded-md">
          {allDomains.map((domain) => (
            <code key={domain} className="text-xs text-gray-600">
              {domain}
            </code>
          ))}
        </div>
      </Card>
    </div>
  );
};
